# Generated by Django 4.0.5 on 2022-07-13 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_dispatcher_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcher',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8bf59891-29b4-4e0e-8459-8c4164edbf4f')),
        ),
    ]
