# Generated by Django 4.0.5 on 2022-07-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_dispatcher_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatcher',
            name='id',
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='uuid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
