# Generated by Django 4.0.5 on 2022-07-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_remove_dispatcher_id_alter_dispatcher_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcher',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
